config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :pictures do 
    collection do 
      post :confirm
    end
  end
  resources :favorites, only: [:index, :create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  validates :image, presence: true
  validates :content, presence: true, length: { maximum: 500 }

  has_many :favorites, dependent: :destroy 
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader

  before_validation { email.downcase! }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password 
  validates :password, length: { minimum: 6 }
  # validates :image, presence: true
  
  has_many :pictures
  
  has_many :favorites, dependent: :destroy 
  has_many :favorite_pictures, through: :favorites, source: :picture #sourceの先はモデル名
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper #railsのすべてのコントローラで使えるようになる
  before_action :login_required

  private 

  def login_required
    redirect_to new_session_path unless current_user #current_userがnilの時、値がない時
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index 
    @favorite = current_user.favorites
  end

  def create 
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログのお気に入りを解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :ensure_current_user, only: [:edit, :update, :destroy]

  def index 
    @pictures = Picture.all
  end

  def new 
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def create
    @picture = current_user.pictures.build(picture_params) #ログインしているユーザのpicturesメソッドをbuild
    render :new and return if params[:back] #return render:new ガード句
    if @picture.save 
      ConfirmMailer.confirm_mail(@picture).deliver
      redirect_to pictures_path, notice: "投稿しました！確認メールを送信しました！"
    else
      render :new
    end
  end

  def show
    @picture = Picture.find(params[:id])
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit 
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "投稿を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_path
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  private 

  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache)
  end
  
  def ensure_current_user
    @picture = Picture.find(params[:id])
    unless @picture.user_id == current_user.id
      flash[:notice]= "権限がありません"
      redirect_to pictures_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create 
    user = User.find_by(email: params[:session][:email].downcase) #ログイン画面で入力されたemailを取得 
    if user && user.authenticate(params[:session][:password])#emailとパスワードが一致していたら
      session[:user_id] = user.id #セッションにユーザーIDを登録する
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :ensure_current_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: "アカウントを作成しました"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "プロフィールを編集しました"
    else
      render :edit
    end
  end

  private 

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end

  def ensure_current_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      flash[:notice]= "権限がありません"
      redirect_to pictures_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper 
  def choose_new_or_edit 
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path 
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<h1>お気に入り一覧</h1>
<div class = "container">
    <div class = "row">
      <div class = "col-md-6 offset-md-3">
        <div class = "card">
          <div class = "card-body">
            <% @favorite.each do |favorite|%>
              <div>
                <p>投稿者: <%= favorite.picture.user.name %></p>
                <p>content: <%= favorite.picture.content %></p>
                <p>image: <%= image_tag favorite.picture.image.url %></p>
              </div>
            <% end %>

          <%= link_to '新規投稿', new_picture_path %>
          <%= link_to '投稿一覧', pictures_path %>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  p img{
    height:200px;
  }

  .card {
    background-color:#edeff0;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class= "navber navbar-expand-lg navbar-light bg-light">
      <% if logged_in? %>
        <div class = "container">
          <button type= "button" class="btn btn-dark btn-sm">
            <i class="bi bi-house-door-fill"></i>
            <%= link_to "Home", pictures_path %>
          </button>
          <button type= "button" class="btn btn-dark btn-sm">
            <i class="bi bi-person-circle"></i>
            <%= link_to "Profile", user_path(current_user.id)%>
          </button>
          <button type= "button" class="btn btn-dark btn-sm">
            <i class="bi bi-box-arrow-right"></i>
            <%= link_to "Logout", session_path(current_user.id), method: :delete %>  
          </button>
        </div>
      <% else %>
        <div class = "container">
          <button type= "button" class="btn btn-dark btn-sm">
            <i class="bi bi-person-plus-fill"></i>
            <%= link_to "Sign up", new_user_path %>
          </button>
          <button type= "button" class="btn btn-dark btn-sm">
            <i class="bi bi-box-arrow-in-right"></i>
            <%= link_to "Login", new_session_path %>
          </button>
        </div>
      <% end %>
    </nav>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class:"#{key}") %>
    <% end %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

<style>
.btn-dark a{
  font-weight:bold;
  color:white;
}
</style>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, url: choose_new_or_edit , local: true) do |f| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this <%= picture.content %> from being saved:</h2>
      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class = "container">
    <div class = "row">
      <div class = "col-md-6 offset-md-3">
        <div class = "card">
          <div class = "card-body">
            <%= f.label :content %>
            <p><%= f.text_field :content %></p>

            <%= f.label :image %>
            <p><%= image_tag( picture.image.url) if picture.image && picture.image.url %></p>
            <p><%= f.file_field :image %></p>
            <%= f.hidden_field :image_cache %>
            
            <p><%= f.submit '投稿する！' %></p>
            <%= link_to '一覧に戻る', pictures_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<style>
  .card {
    background-color:#edeff0;
  }
  p img{
    height:200px;
  }
</style>

app/views/pictures/confirm.html.erb
<h1>確認</h1>

<div class = "container">
  <div class = "row">
    <div class = "col-md-6 offset-md-3">
      <div class = "card">
        <div class = "card-body">
          <%= form_with(model: @picture, url:pictures_path , local: true) do |f| %>
            <p>content: <%= @picture.content %></p>
            <p>image: <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></p>
            <%= f.submit '投稿する！' %>
            <%= f.hidden_field :content %>
            <%= f.hidden_field :image_cache %>
          <% end %>
          <%= form_with(model: @picture, url:new_picture_path, local:true, method:"get") do |f| %>
            <%= f.hidden_field :image_cache %>
            <%= f.submit '戻る', name: 'back' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  p img{
    height:200px;
  }

  .card {
    background-color:#edeff0;
  }
</style>

app/views/pictures/edit.html.erb
<h1>編集画面</h1>
<%= render 'form', picture: @picture %>

app/views/pictures/index.html.erb
<!--<h1>投稿一覧</h1>-->
  <!--<p><%= notice %></p>-->

<button class="btn btn-primary">
  <i class="bi bi-plus-square"></i>
  <%= link_to 'New Post', new_picture_path %>
</button>

<!--
<button class="btn">
  <i class="bi bi-house-door-fill"></i>
  <%= link_to 'Home', pictures_path %>
</button>
-->
<div class = "container">
  <table class="table table-sm">
    <% @pictures.each do |picture|%>
    <tr>
      <td>
        <div class = "profile_image">
          <%= image_tag picture.user.image.url %>
          <%= picture.user.name %>
        </div>
        <div class = "content_image">
          <%= image_tag picture.image.url %><br>
          <%= picture.content %>
        </div>
      
        <div class>
          <button class = "btn btn-outline-secondary btn-sm">
            <%= link_to '詳細', picture_path(picture.id) %>
          </button>
          <% if picture.user_id == current_user.id %> 
            <button class = "btn btn-outline-secondary btn-sm">
              <%= link_to '編集', edit_picture_path(picture.id), data:{ confirm:'本当に編集していいですか？'} %>
            </button>
            <button class = "btn btn-outline-secondary btn-sm">
              <%= link_to '削除', picture_path(picture.id), method: :delete, data:{ confirm:'本当に削除していいですか？'} %>
            </button>
          <% end %>
        </div>
      </td>
    </tr>
    <% end %>
  </div>
</table>

<style>
.content_image{
  margin:20px 0;
  text-align:center;
}
.content_image img{
  height:250px;
  width:250px;
}
button{
  margin:15px auto;
}
.btn btn-primary a{
  color: #ffffff;
}
.profile_image img{
  height:50px;
  width:50px;
  border-radius:50%;
  border:solid 1px #f758fc;
}
img{
  object-fit:cover;
}
.container{
  max-width:576px;
}
.btn-outline-secondary a{
  color:grey;
}
.btn-primary a{
  color:white;
}
</style>

<!--
<% @pictures.each do |picture|%>
  <tr>
    <td class = "profile_image">
      <%= picture.user.name %><br>
      <%= image_tag picture.user.image.url %>
    </td>
    <td><%= picture.content %></td>
    <td><%= image_tag picture.image.url %></td>
    <td><%= link_to '詳細', picture_path(picture.id) %>
    <% if picture.user_id == current_user.id %> 
      <%= link_to '編集', edit_picture_path(picture.id), data:{ confirm:'本当に編集していいですか？'} %>
      <%= link_to '削除', picture_path(picture.id), method: :delete, data:{ confirm:'本当に削除していいですか？'} %></td>
    <% end %>
  </tr>
  <% end %>
</table>
-->

app/views/pictures/new.html.erb
<h1>新規作成</h1>
<%= render 'form', picture: @picture %>

app/views/pictures/show.html.erb
<h1>詳細</h1>

<div class = "container">
  <div class = "row">
    <div class = "col-md-6 offset-md-3">
      <div class = "card">
        <div class = "card-body">
          <p>content: <%= @picture.content %></p>
          <p>image: <%= image_tag @picture.image.url %></p>

          <% unless @picture.user_id == current_user.id %> <!--ブログを書いた人と、ログイン中のユーザが同じでない時-->
            <% if @favorite.present? %>
              <%= link_to "お気に入りを解除する", favorite_path(id: @favorite.id), method: :delete, class:"btn btn-danger" %> <!--classはboostrapのものと思われる-->
            <% else%>
              <%= link_to "お気に入りする", favorites_path(picture_id: @picture.id), method: :post, class:"btn btn-primary" %>
            <% end %>
          <% end %>

          <% if @picture.user_id == current_user.id %> <!--ユーザーIDの一致がtrueの時に表示-->
            <%= link_to "Edit", edit_picture_path(@picture.id) %>
          <% end %>
          <br>
          <%= link_to "Back", pictures_path %>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  p img{
    height:200px;
  }

  .card {
    background-color:#edeff0;
  }
</style>

app/views/users/edit.html.erb
<h1>Edit</h1>

<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class = "container">
  <div class = "row">
    <div class = "col-md-6 offset-md-3">
      <div class = "card">
        <div class = "card-body">
          <%= f.label :name %>
          <p><%= f.text_field :name %></p>

          <%= f.label :email %>
          <p><%= f.text_field :email %></p>

          <%= f.label :password  %>
          <p><%= f.text_field :password %></p>

          <%= f.label :password_confirmation %>
          <p><%= f.text_field :password_confirmation %></p>
          
          <%= f.label :image %>
          <p><%= f.file_field :image %></p>

          <p><%= f.submit '更新する！' %></p>
<% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  p img{
    height:200px;
  }

  .card {
    background-color:#edeff0;
  }
</style>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class = "container">
  <div class = "row">
    <div class = "col-md-6 offset-md-3">
      <div class = "card">
        <div class = "card-body">
          <%= f.label :name %>
          <p><%= f.text_field :name %></p>

          <%= f.label :email %>
          <p><%= f.text_field :email %></p>

          <%= f.label :password  %>
          <p><%= f.text_field :password %></p>
        
          <%= f.label :password_confirmation %>
          <p><%= f.text_field :password_confirmation %></p>

          <%= f.label :image %>
          <p><%= f.file_field :image %></p>
      
          <p><%= f.submit 'アカウントを作成する！' %></p>
          
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<style>
p {
  width:100%;
  height:30px;
}
p input{
  width:100%;
}
body{
  background-color:#f0f5f4;
}
</style>

app/views/users/show.html.erb
<h1><%= @user.name%>さんのProfile</h1>

<div class = "container">
  <div class = "row">
    <div class = "col-md-6 offset-md-3">
      <div class = "card">
        <div class = "card-body">
          <p>name: <%= @user.name %></p>
          <p>email: <%= @user.email %></p>
          <p>image: <%= image_tag @user.image.url %></p>
          <% if @user.id == current_user.id %>
            <button class = "btn btn-secondary btn-sm">
              <%= link_to "編集", edit_user_path(@user.id), data: { confirm: '本当に編集していいですか？'} %>
            </button>
          <% end %>
          <button class = "btn btn-secondary btn-sm">
            <%= link_to "お気に入り一覧", favorites_path %>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  p img{
    height:200px;
  }

  .card {
    background-color:#edeff0;
  }
  .btn-secondary a{
    color:white;
  }
</style>